---
3574_vob_mcu_dora_7.7.0.1.0:
- m:/vtrofymyuk_view1/mcu/Doc/Scopia_Elite_Demo_Instructions.docx
- m:/vtrofymyuk_view1/mcu/Doc/versions.xml
- m:/vtrofymyuk_view1/mcu/EC/Build/tornado/EC.wpj
- m:/vtrofymyuk_view1/mcu/GCC/Build/tornado/GCC.wpj
- m:/vtrofymyuk_view1/mcu/Main/Mib/MibCompiler/ViaIP_MCU_MIB_5_0.doc
- m:/vtrofymyuk_view1/mcu/Main/Mib/MibCompiler/ViaIP_MCU_MIB_5_1.doc
- m:/vtrofymyuk_view1/mcu/Main/Mib/mcuVxMibFunc.c
- m:/vtrofymyuk_view1/mcu/Main/Mib/mcuWinMibFunc.c
- m:/vtrofymyuk_view1/mcu/XML/Build/tornado/XMLController.wpj
278_vob_web_WebMcu_7.5.1_21_270311.470:
- m:/vtrofymyuk_view1/web/Doc/Old/WebReleaseNotes7.0.xlsx
- m:/vtrofymyuk_view1/web/Doc/Old/WebReleaseNotes7.1.xlsx
- m:/vtrofymyuk_view1/web/Doc/Old/WebReleaseNotes7.1.2.xlsx
- m:/vtrofymyuk_view1/web/Doc/Old/WebReleaseNotes7.2.xlsx
- m:/vtrofymyuk_view1/web/WebClient/Scripts/common/core/data/data.all.js.min.js
- m:/vtrofymyuk_view1/web/WebServer/WebFlash/tools/RunDir/versions/WEB_flash_compressed.fls
7661_vob_mf_dora_mf_7.6.0.6.0:
- m:/vtrofymyuk_view1/mf/Externals/AudioMixer/Docs/How to Add a new CNG data array
  to the mixer.doc
- m:/vtrofymyuk_view1/mf/Simulation/Players/lib/VxWorks/MFSimPlayer/DEBUG/MFSimPlayer.out
- m:/vtrofymyuk_view1/mf/Simulation/Players/lib/VxWorks/MFSimPlayer/RELEASE/MFSimPlayer.out
- m:/vtrofymyuk_view1/mf/Simulation/Players/jittertester/debug/jittertester.pdb
1109_vob_mpInfra_mpInfra_dora_7.6.0.0.0:
- m:/vtrofymyuk_view1/mpInfra/Test/Debug/rvsip.pdb
- m:/vtrofymyuk_view1/mpInfra/Test/Debug/rvsip.dll
- m:/vtrofymyuk_view1/mpInfra/Test/Debug/rvcommon.pdb
- m:/vtrofymyuk_view1/mpInfra/Test/Debug/Test.pdb
4155_vob_mpDsp_dora_mpDsp_7.6.0.3.0:
- m:/vtrofymyuk_view1/mpDsp/HDI/test/d2d/inFile.in
- m:/vtrofymyuk_view1/mpDsp/HDI/test/d2h/inFile.in
- m:/vtrofymyuk_view1/mpDsp/HDI/test/d2h_multi/inFile.in
- m:/vtrofymyuk_view1/mpDsp/HDI/test/windows/inFile.in
6452_vob_mvp_dora_mvp_7.7.0.0.0:
- m:/vtrofymyuk_view1/mvp/Release/mvp-pkg/Data/Font/H2GPRM.TTF
- m:/vtrofymyuk_view1/mvp/Release/mvp-pkg/Data/Font/HGRSMP.TTF
- m:/vtrofymyuk_view1/mvp/Release/mvp-pkg/Data/Font/bsyh00ms.ttf
- m:/vtrofymyuk_view1/mvp/Release/mvp-pkg/Data/Font/simkai.ttf
- m:/vtrofymyuk_view1/mvp/Release/mvp-pkg/Data/Font/Daum_Regular.ttf
- m:/vtrofymyuk_view1/mvp/Govl/FT_restricted/ARIALUNI.TTF
- m:/vtrofymyuk_view1/mvp/Govl/FT_restricted/blue_new.yuv
- m:/vtrofymyuk_view1/mvp/Govl/FT_restricted/htst3.ttf
- m:/vtrofymyuk_view1/mvp/Govl/FT_restricted/simkai.ttf
- m:/vtrofymyuk_view1/mvp/Govl/Resources/arialArr.c
- m:/vtrofymyuk_view1/mvp/Govl/Resources/simkaiarr.c
2292_vob_NBU_COMMON_CORE_nbuCCore_4.2.0:
- m:/vtrofymyuk_view1/NBU_COMMON_CORE/release/bin/rv-linux-ppc-debug/nbu-ccore-common.a
- m:/vtrofymyuk_view1/NBU_COMMON_CORE/release/bin/rv-linux-ppc-opt/nbu-ccore-common.a
- m:/vtrofymyuk_view1/NBU_COMMON_CORE/release/bin/rv-linux-x86-debug/nbu-ccore-common.a
- m:/vtrofymyuk_view1/NBU_COMMON_CORE/release/bin/rv-win32-debug/nbu-ccore-ads.pdb
- m:/vtrofymyuk_view1/NBU_COMMON_CORE/release/bin/rv-win32-debug/nbu-ccore-common.dll
- m:/vtrofymyuk_view1/NBU_COMMON_CORE/release/bin/rv-win32-debug/nbu-ccore-common.pdb
7288_vob_NBU_H323_STACK_itayb_7.5.1.10.4_H323Fix:
- m:/vtrofymyuk_view1/NBU_H323_STACK/release/bin/rv-linux-ppc-debug/nbu-h323-stack-h245.a
- m:/vtrofymyuk_view1/NBU_H323_STACK/release/bin/rv-linux-ppc-debug/nbu-h323-stack.a
- m:/vtrofymyuk_view1/NBU_H323_STACK/release/bin/rv-linux-ppc-opt/nbu-h323-stack-h245.a
- m:/vtrofymyuk_view1/NBU_H323_STACK/release/bin/rv-linux-ppc-opt/nbu-h323-stack.a
- m:/vtrofymyuk_view1/NBU_H323_STACK/release/bin/rv-linux-x86-debug/nbu-h323-stack.a
- m:/vtrofymyuk_view1/NBU_H323_STACK/release/bin/rv-win32-debug/nbu-h323-stack-asn1.pdb
- m:/vtrofymyuk_view1/NBU_H323_STACK/release/bin/rv-win32-debug/nbu-h323-stack-h235.pdb
- m:/vtrofymyuk_view1/NBU_H323_STACK/release/bin/rv-win32-debug/nbu-h323-stack-h245.lib
- m:/vtrofymyuk_view1/NBU_H323_STACK/release/bin/rv-win32-debug/nbu-h323-stack.dll
- m:/vtrofymyuk_view1/NBU_H323_STACK/release/bin/rv-win32-debug/nbu-h323-stack.pdb
- m:/vtrofymyuk_view1/NBU_H323_STACK/release/bin/rv-win32-opt/nbu-h323-stack.pdb
- m:/vtrofymyuk_view1/NBU_H323_STACK/rvh323/appl/lib/OpenLDAP/oldap32.lib
- m:/vtrofymyuk_view1/NBU_H323_STACK/rvh323/build/ActiveTcl8.4.9.0.121397-win32-ix86.exe
3304_vob_NBU_SIP_STACK_nbuSip_4.2.0_dora-7.5.1_2.2:
- m:/vtrofymyuk_view1/NBU_SIP_STACK/release/bin/rv-linux-ppc-debug/nbu-sip-stack.a
- m:/vtrofymyuk_view1/NBU_SIP_STACK/release/bin/rv-linux-ppc-opt/nbu-sip-stack-sdp.a
- m:/vtrofymyuk_view1/NBU_SIP_STACK/release/bin/rv-linux-ppc-opt/nbu-sip-stack.a
- m:/vtrofymyuk_view1/NBU_SIP_STACK/release/bin/rv-linux-x86-debug/nbu-sip-stack.a
- m:/vtrofymyuk_view1/NBU_SIP_STACK/release/bin/rv-win32-debug/nbu-sip-stack.dll
- m:/vtrofymyuk_view1/NBU_SIP_STACK/release/bin/rv-win32-debug/nbu-sip-stack-offerAnswer.pdb
- m:/vtrofymyuk_view1/NBU_SIP_STACK/release/bin/rv-win32-debug/nbu-sip-stack-sdp.pdb
- m:/vtrofymyuk_view1/NBU_SIP_STACK/release/bin/rv-win32-debug/nbu-sip-stack.pdb
- m:/vtrofymyuk_view1/NBU_SIP_STACK/release/bin/rv-win32-debug/nbu-sip-stack-bfcp.pdb
- m:/vtrofymyuk_view1/NBU_SIP_STACK/release/bin/rv-win32-opt/nbu-sip-stack.dll
- m:/vtrofymyuk_view1/NBU_SIP_STACK/rvsip/binaries/vxworks_2.2/ReleaseDns/bin/advancedDNSSession.out
- m:/vtrofymyuk_view1/NBU_SIP_STACK/rvsip/binaries/vxworks_2.2/ReleaseDns/bin/advancedTransfer.out
- m:/vtrofymyuk_view1/NBU_SIP_STACK/rvsip/binaries/vxworks_2.2/ReleaseDns/bin/simpleAuthentication.out
- m:/vtrofymyuk_view1/NBU_SIP_STACK/rvsip/binaries/vxworks_2.2/ReleaseDns/bin/simpleInfo.out
- m:/vtrofymyuk_view1/NBU_SIP_STACK/rvsip/binaries/vxworks_2.2/ReleaseDns/bin/simpleParserControl.out
- m:/vtrofymyuk_view1/NBU_SIP_STACK/rvsip/binaries/vxworks_2.2/ReleaseDns/bin/simplePersistentConnection.out
- m:/vtrofymyuk_view1/NBU_SIP_STACK/rvsip/binaries/vxworks_2.2/ReleaseDns/bin/simpleProxy.out
- m:/vtrofymyuk_view1/NBU_SIP_STACK/rvsip/binaries/vxworks_2.2/ReleaseDns/bin/simpleRFC2833.out
- m:/vtrofymyuk_view1/NBU_SIP_STACK/rvsip/binaries/vxworks_2.2/ReleaseDns/bin/simpleRegistration.out
- m:/vtrofymyuk_view1/NBU_SIP_STACK/rvsip/binaries/vxworks_2.2/ReleaseDns/bin/simpleSIPT.out
- m:/vtrofymyuk_view1/NBU_SIP_STACK/rvsip/binaries/vxworks_2.2/ReleaseDns/bin/simpleServerAuth.out
- m:/vtrofymyuk_view1/NBU_SIP_STACK/rvsip/binaries/vxworks_2.2/ReleaseDns/bin/simpleSession.out
- m:/vtrofymyuk_view1/NBU_SIP_STACK/rvsip/binaries/vxworks_2.2/ReleaseDns/bin/simpleSessionSDP.out
- m:/vtrofymyuk_view1/NBU_SIP_STACK/rvsip/binaries/vxworks_2.2/ReleaseDns/bin/simpleSubscription.out
- m:/vtrofymyuk_view1/NBU_SIP_STACK/rvsip/binaries/vxworks_2.2/ReleaseDns/bin/simpleTransaction.out
- m:/vtrofymyuk_view1/NBU_SIP_STACK/rvsip/binaries/vxworks_2.2/ReleaseDns/bin/simpleTransfer.out
- m:/vtrofymyuk_view1/NBU_SIP_STACK/rvsip/binaries/vxworks_2.2/ReleaseDns/bin/simpleUpdate.out
- m:/vtrofymyuk_view1/NBU_SIP_STACK/rvsip/binaries/windows/releaseDns/bin/siptestapp.ilk
- m:/vtrofymyuk_view1/NBU_SIP_STACK/rvsip/build/ActiveTcl8.4.9.0.121397-win32-ix86.exe
- m:/vtrofymyuk_view1/NBU_SIP_STACK/rvsip/sip/parser/ParserEngineClassic2.h
- m:/vtrofymyuk_view1/NBU_SIP_STACK/rvsip/sip/parser/ParserEngineIMS2.h
- m:/vtrofymyuk_view1/NBU_SIP_STACK/rvsip/sip/parser/ParserEngineTel2.h
4211_vob_boardInfra_boardInfra_0.75.0_dora-7.6.0.3.0:
- m:/vtrofymyuk_view1/boardInfra/NbuUpgradeModule/iInstaller/res/UpgradePack_7_1_2.pkg
- m:/vtrofymyuk_view1/boardInfra/NbuUpgradeModule/iInstaller/res/UpgradePack_7_5.pkg
- m:/vtrofymyuk_view1/boardInfra/NbuUpgradeModule/iInstaller/res/vx-to-linux-flash-files.zip
8109_vob_securityApp_securityApp_0.10.2:
- m:/vtrofymyuk_view1/securityApp/OpenSSL/0.9.8m/windows/libeay32.dll
3324_vob_securityInfra_110301_SECURITY2_V5.0_13:
- m:/vtrofymyuk_view1/securityInfra/docs/MOCANA/Integration_Guide.pdf
- m:/vtrofymyuk_view1/securityInfra/docs/MOCANA/mss_api_doc.zip
- m:/vtrofymyuk_view1/securityInfra/docs/tls API description.doc
9062_vob_bspLinux8548_110504_MAIO_0.2.44:
- m:/vtrofymyuk_view1/bspLinux8548/Release/RVsoTest/dora-glibc_small-ppc_e500v2-wrlinux_2_0/Debug/RVsoTest.out
- m:/vtrofymyuk_view1/bspLinux8548/Release/RVsoTest/dora-glibc_small-ppc_e500v2-wrlinux_2_0/NonDebug/RVsoTest.out
- m:/vtrofymyuk_view1/bspLinux8548/Release/Platform/Filesystem/dora-glibc_cgl-small-dist.tar.bz2
- m:/vtrofymyuk_view1/bspLinux8548/Release/Platform/Filesystem/initramfs_data-all.cpio
- m:/vtrofymyuk_view1/bspLinux8548/Release/Platform/Filesystem/dora-glibc_cgl-small-dist-ext2.image.bzip2
- m:/vtrofymyuk_view1/bspLinux8548/Release/Platform/Kernel/Dora/dora-uImage-WR2.0bl_small
- m:/vtrofymyuk_view1/bspLinux8548/Release/Platform/Kernel/Dora/dora-uImage-WR2.0bl_small-disassemble.bzip2
- m:/vtrofymyuk_view1/bspLinux8548/Release/Platform/Kernel/Tamar/wrs_sbc8548-uImage-WR2.0bl_standard
- m:/vtrofymyuk_view1/bspLinux8548/Release/Platform/Kernel/Tamar/wrs_sbc8548-uImage-WR2.0bl_standard_initramfs
- m:/vtrofymyuk_view1/bspLinux8548/Release/Platform/Sysroot/dora-glibc_cgl.tar.bz2
- m:/vtrofymyuk_view1/bspLinux8548/Release/Platform/Sysroot/dora-glibc_small.tar.bz2
- m:/vtrofymyuk_view1/bspLinux8548/Release/Platform/DVT/Filesystem/dora-glibc_cgl-small-dist-ext2.image.bzip2
- m:/vtrofymyuk_view1/bspLinux8548/Release/Platform/DVT/Kernel/Dora/dora-uImage-WR2.0bl_small
- m:/vtrofymyuk_view1/bspLinux8548/Release/Platform/DVT/Kernel/Dora/dora-uImage-WR2.0bl_small-disassemble.bzip2
- m:/vtrofymyuk_view1/bspLinux8548/Release/Platform/DVT/U-boot/Dora/u-boot.bin
- m:/vtrofymyuk_view1/bspLinux8548/Release/Platform/DVT/U-boot/Dora/u-boot_brc.bin
- m:/vtrofymyuk_view1/bspLinux8548/Release/Platform/DVT/flash-FS-splitted/f0_dora-glibc_cgl-small-dist-ext2.0
- m:/vtrofymyuk_view1/bspLinux8548/Release/Platform/DVT/flash-FS-splitted/f121_vxworks_linux.brc
- m:/vtrofymyuk_view1/bspLinux8548/Release/Platform/DVT/flash-FS-splitted/f12_dora-glibc_cgl-small-dist-ext2.4
- m:/vtrofymyuk_view1/bspLinux8548/Release/Platform/DVT/flash-FS-splitted/f15_dora-glibc_cgl-small-dist-ext2.5
- m:/vtrofymyuk_view1/bspLinux8548/Release/Platform/DVT/flash-FS-splitted/f3_dora-glibc_cgl-small-dist-ext2.1
- m:/vtrofymyuk_view1/bspLinux8548/Release/Platform/DVT/flash-FS-splitted/f6_dora-glibc_cgl-small-dist-ext2.2
- m:/vtrofymyuk_view1/bspLinux8548/Release/Platform/DVT/flash-FS-splitted/f9_dora-glibc_cgl-small-dist-ext2.3
- m:/vtrofymyuk_view1/bspLinux8548/Release/Platform/DVT/flash-FS-splitted/k105_uImage.brc
- m:/vtrofymyuk_view1/bspLinux8548/Release/Platform/DVT/flash-FS-splitted/u-boot_brc.bin
- m:/vtrofymyuk_view1/bspLinux8548/Release/Platform/DVT/Etc/srioTest.bin
- m:/vtrofymyuk_view1/bspLinux8548/Release/Platform/DVT/Etc/srioTest_noRionet.bin
- m:/vtrofymyuk_view1/bspLinux8548/U-boot/u-boot-1.3.4-rc1.tar.bz2
- m:/vtrofymyuk_view1/bspLinux8548/Tools/Utils/host/file-splitter/BinSplitSU.EXE
- m:/vtrofymyuk_view1/bspLinux8548/Tools/Utils/target/busybox-1.13.1.tar.gz
- m:/vtrofymyuk_view1/bspLinux8548/Tools/Utils/target/valgrind-3.3.1.tar.bz2
- m:/vtrofymyuk_view1/bspLinux8548/Tools/Utils/target/libs/libc-2.5.so
- m:/vtrofymyuk_view1/bspLinux8548/Tools/Patches/pf_ring.tar.bz2
- m:/vtrofymyuk_view1/bspLinux8548/Tools/Patches/pf_ring_org.tar.bz2
- m:/vtrofymyuk_view1/bspLinux8548/Platform/Layers/tamar/packages/gdb-6.6.tar.bz2
- m:/vtrofymyuk_view1/bspLinux8548/Platform/Layers/tamar/packages/valgrind-3.3.1.tar.bz2
- m:/vtrofymyuk_view1/bspLinux8548/Platform/Layers/tamar/packages/gdb-6.8.tar.bz2
- m:/vtrofymyuk_view1/bspLinux8548/Platform/Layers/tamar/packages/openssl-1.0.0.tar.gz
- m:/vtrofymyuk_view1/bspLinux8548/Platform/Layers/tamar/packages/openssl-fips-1.2.tar.gz
- m:/vtrofymyuk_view1/bspLinux8548/Platform/Layers/tamar/templates/default/linux/2.6.x/linux-2.6.21-standard.diff
- m:/vtrofymyuk_view1/bspLinux8548/RVCryptoTest/securityInfra-mocana-common.a
- m:/vtrofymyuk_view1/bspLinux8548/RVCryptoTest/securityInfra-mocana-crypto.a
- m:/vtrofymyuk_view1/bspLinux8548/Host/home/wruser/WindRiver/wrlinux-2.0/wrlinux/configure
6000_vob_freemasonBuild_freemasonBuild_1.2.9:
- m:/vtrofymyuk_view1/freemasonBuild/freemason/4/doc/user-guide/cover2.pdf
- m:/vtrofymyuk_view1/freemasonBuild/freemason/4/doc/presentation/Introduction to
  Freemason.ppt
- m:/vtrofymyuk_view1/freemasonBuild/freemason/4/bin/windows/cc1.exe
